---
- name: install deps
  apt:
    name:
      - git
  become: true

- name: clone jitsi-meet
  git:
    repo: "{{ jitsi_meet__repo }}"
    dest: "{{ jitsi_meet__install_dir }}"
    version: "{{ jitsi_meet__version }}"
  become: true
  notify: restart docker-compose

- name: config dir
  file:
    path: "{{ jitsi_meet__config_dir }}/{{ item }}"
    state: directory
  become: true
  loop:
    - web
    - letsencrypt
    - transcripts
    - prosody
    - jicofo
    - jvb

- name: env file
  template:
    src: env.j2
    dest: "{{ jitsi_meet__install_dir }}/.env"
  become: true
  notify: restart docker-compose

- name: start jitsi
  command: docker-compose up -d
  args:
    chdir: "{{ jitsi_meet__install_dir }}"
  become: true

- name: stats
  docker_container:
    name: jitsiexporter
    image: quay.io/xsteadfastx/jitsiexporter:latest
    pull: true
    ports:
      - "0.0.0.0:6700:6700"
    networks:
      - name: jitsi-meet_meet.jitsi
    command: --url http://jitsi-meet_jvb_1:8080/colibri/stats
