---
- name: install deps
  apt:
    name:
      - git
  become: true

- name: clone jitsi-meet
  git:
    repo: "{{ jitsi_meet__repo }}"
    dest: "{{ jitsi_meet__install_dir }}"
    version: "{{ jitsi_meet__version }}"
  become: true
  notify:
    - recreate

- name: env file
  template:
    src: env.j2
    dest: "{{ jitsi_meet__install_dir }}/.env"
  become: true
  notify:
    - recreate
