---
- block:
  - name: remove exporter container
    docker_container:
      name: jitsiexporter
      image: quay.io/xsteadfastx/jitsiexporter:latest
      state: absent
    become: true

  - name: remove cfg dirs
    file:
      path: "{{ jitsi_meet__config_dir }}/{{ item }}"
      state: absent
    become: true
    notify: create passwords
    loop:
      - jicofo
      - jvb
      - prosody
      - transcripts

  - name: create passwords
    command: "bash gen-passwords.sh"
    args:
      chdir: "{{ jitsi_meet__install_dir }}"
    become: true

  - name: pull fresh docker images
    command: "docker-compose pull"
    args:
      chdir: "{{ jitsi_meet__install_dir }}"
    become: true

  - name: restart docker-compose
    command: "docker-compose up -d --force-recreate --remove-orphans"
    args:
      chdir: "{{ jitsi_meet__install_dir }}"
    become: true

  - name: start exporter
    docker_container:
      name: jitsiexporter
      image: quay.io/xsteadfastx/jitsiexporter:latest
      pull: true
      recreate: true
      ports:
        - "0.0.0.0:9700:9700"
      networks:
        - name: jitsi-meet_meet.jitsi
      restart_policy: always
      command: --url http://jitsi-meet_jvb_1:8080/colibri/stats
