---
- name: recreate
  docker_container:
    name: jitsiexporter
    image: quay.io/xsteadfastx/jitsiexporter:latest
    state: absent
  become: true
  notify: create passwords

- name: create passwords
  command: "bash gen-passwords.sh"
  args:
    chdir: "{{ jitsi_meet__install_dir }}"
  become: true
  notify: restart docker-compose

- name: restart docker-compose
  command: "docker-compose up --force-recreate --remove-orphans"
  args:
    chdir: "{{ jitsi_meet__install_dir }}"
  become: true

- name: start exporter
  docker_container:
    name: jitsiexporter
    image: quay.io/xsteadfastx/jitsiexporter:latest
    pull: true
    recreate: true
    ports:
      - "0.0.0.0:9700:9700"
    networks:
      - name: jitsi-meet_meet.jitsi
    command: --url http://jitsi-meet_jvb_1:8080/colibri/stats
